# Generated by Django 2.1.2 on 2019-01-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cookbox_core", "0002_auto_20181111_1333"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ingredient",
            name="usda_code",
        ),
    ]
