# Generated by Django 2.1.2 on 2019-01-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbox_core", "0003_remove_ingredient_usda_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="recipe",
            name="description",
            field=models.CharField(default="", max_length=1024),
        ),
    ]
