# Generated by Django 2.1.2 on 2019-01-08 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbox_core', '0004_auto_20190105_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
