# Generated by Django 2.1.5 on 2019-03-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbox_core', '0008_remove_tag_recipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='recipes',
            field=models.ManyToManyField(related_name='tags', to='cookbox_core.Recipe'),
        ),
    ]
