# Generated by Django 2.1.7 on 2019-04-24 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cookbox_core", "0008_remove_tag_recipe"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=126, unique=True),
        )
    ]
