# Generated by Django 2.1.7 on 2019-07-21 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbox_core', '0011_auto_20190713_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='unit_time',
            field=models.CharField(choices=[('sec.', 'seconds'), ('min.', 'minutes'), ('hrs.', 'hours'), ('days', 'days'), ('weeks', 'weeks'), ('months', 'month'), ('years', 'years')], default='min.', max_length=126),
        ),
    ]
