version: "3.3"

services:
    web:
        build: .
        restart: always
        ports:
            - "80:80" # HOST:CONTAINER
        environment:
            - DEBUG=${DEBUG}
            - SECRET_KEY=${SECRET_KEY}
            - ALLOWED_HOSTS=${SERVER_NAME} ${SERVER_ALIAS}
            - DB_ENGINE=${DB_ENGINE}
            - SERVER_NAME=${SERVER_NAME}
            - SERVER_ALIAS=${SERVER_ALIAS}
            - SERVER_ADMIN_EMAIL=${SERVER_ADMIN_EMAIL}
        volumes:
            - ./data:/opt/cookbox/data
