# Generated by Django 2.1 on 2018-08-17 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cb_database', '0002_auto_20180817_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='time',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='yield_size',
        ),
        migrations.AddField(
            model_name='timeinfo',
            name='recipe',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cb_database.Recipe'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='yieldinfo',
            name='recipe',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='cb_database.Recipe'),
            preserve_default=False,
        ),
    ]
