# Generated by Django 2.1 on 2018-08-18 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cb_database', '0003_auto_20180817_0744'),
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('text', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Instruction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instruction', models.CharField(default='', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='InstructionNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('text', models.CharField(default='', max_length=256)),
                ('instruction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cb_database.Instruction')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecipeNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='')),
                ('text', models.CharField(default='', max_length=256)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='ingredient',
            name='basic_ingredient',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='description',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='other_recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cb_database.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='usda_code',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cb_database.Recipe'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredient_groups', to='cb_database.Recipe'),
        ),
        migrations.AlterField(
            model_name='timeinfo',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='time_info', to='cb_database.Recipe'),
        ),
        migrations.AlterField(
            model_name='yieldinfo',
            name='recipe',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yield_info', to='cb_database.Recipe'),
        ),
        migrations.DeleteModel(
            name='BasicIngredient',
        ),
        migrations.AddField(
            model_name='recipenote',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cb_database.Recipe'),
        ),
        migrations.AddField(
            model_name='instruction',
            name='recipe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructions', to='cb_database.Recipe'),
        ),
        migrations.AddField(
            model_name='ingredientnote',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='cb_database.Ingredient'),
        ),
    ]
