# Generated by Django 2.1 on 2018-08-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_database', '0005_auto_20180820_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yieldinfo',
            name='serving_size',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='yieldinfo',
            name='total_yield',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
