# Generated by Django 2.1 on 2018-08-22 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_database', '0006_auto_20180820_1649'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='other_recipe',
        ),
        migrations.AlterField(
            model_name='ingredientnote',
            name='text',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='instructionnote',
            name='text',
            field=models.CharField(default='', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='recipenote',
            name='text',
            field=models.CharField(default='', max_length=256, null=True),
        ),
    ]
