# Generated by Django 2.1 on 2018-08-26 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cb_database', '0007_auto_20180822_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='recipe',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='cb_database.IngredientGroup'),
        ),
        migrations.AlterField(
            model_name='ingredientgroup',
            name='name',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
