# Generated by Django 2.1 on 2018-08-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_database', '0008_auto_20180826_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='unit',
            field=models.CharField(default='g', max_length=256),
            preserve_default=False,
        ),
    ]
