# Generated by Django 2.1.1 on 2018-09-21 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cb_database', '0011_auto_20180827_0840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeinfo',
            name='recipe',
        ),
        migrations.RemoveField(
            model_name='yieldinfo',
            name='recipe',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cook_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='preparation_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='serving_size',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_time',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='total_yield',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit_time',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recipe',
            name='unit_yield',
            field=models.CharField(default=0, max_length=256),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TimeInfo',
        ),
        migrations.DeleteModel(
            name='YieldInfo',
        ),
    ]
