# Generated by Django 4.1.3 on 2025-02-16 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cookbox_seasons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeasonsItem',
        ),
    ]
